enum ActionTypes {
  INCREMENT_TICKETS_STANDARD = 'INCREMENT_TICKETS_STANDARD',
  INCREMENT_TICKETS_PREMIUM = 'INCREMENT_TICKETS_PREMIUM',
  INCREMENT_TICKETS_VIP = 'INCREMENT_TICKETS_VIP',

  DECREMENT_TICKETS_STANDARD = 'DECREMENT_TICKETS_STANDARD',
  DECREMENT_TICKETS_PREMIUM = 'DECREMENT_TICKETS_PREMIUM',
  DECREMENT_TICKETS_VIP = 'DECREMENT_TICKETS_VIP',

  RESET_TICKETS_STANDARD = 'RESET_TICKETS_STANDARD',
  RESET_TICKETS_PREMIUM = 'RESET_TICKETS_PREMIUM',
  RESET_TICKETS_VIP = 'RESET_TICKETS_VIP'
}

export default ActionTypes;
